name: realest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  image: ^4.3.0
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.11.0
  path_provider: ^2.0.11
  excel: ^4.0.6
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  intl: ^0.20.1
  animated_text_kit: ^4.2.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/AUTOSCAN-removebg-preview.png
    - assets/car dataset.xlsx
    - assets/VGG16Model3.tflite
    - assets/VGG16Model2.tflite
    - assets/VGG16NameList.txt
    - assets/finalModel.tflite
    - assets/FinalList.txt
    - assets/ModelC.tflite
    - assets/ModelA_GB.tflite
    - assets/GBFINAL.txt
  uses-material-design: true
