name: realest
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  image_picker: ^1.1.2
  image: ^4.3.0
  cupertino_icons: ^1.0.2
  tflite_flutter: ^0.11.0
  path_provider: ^2.0.11
  excel: ^4.0.6
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  intl: ^0.18.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/AUTOSCAN-removebg-preview.png
    - assets/car_classifier_model.tflite
    - assets/car_classifier_model2.tflite
    - assets/listNEW.txt
    - assets/listNEW2.txt
    - assets/car dataset.xlsx
  uses-material-design: true
